version: '3'
services:

  #PHP Service
  app:
    build:
      context: ${SRC_PATH}
      dockerfile: docker/Dockerfile
      args:
        DOCKER_USER: ${DOCKER_USER}
        DOCKER_USER_GROUP: ${DOCKER_USER_GROUP}
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      DOCKER_USER: ${DOCKER_USER}
      DOCKER_USER_GROUP: ${DOCKER_USER_GROUP}
    working_dir: /var/www
    volumes:
      - ${SRC_PATH}/:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  webserver:
    image: nginx:1.17.6
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${SRC_PATH}/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  #MySQL Service
  db:
    image: mysql:8
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql-files:/var/lib/mysql-files

#Volumes
volumes:
  dbdata:
    driver: local
